from enum import Enum
from typing import Dict, Any, List, Optional
from pydantic import BaseModel, Field

class RequestIntent(str, Enum):
    # Action Intents
    CREATE_TASK = "CREATE_TASK"
    UPDATE_TASK = "UPDATE_TASK"
    COMPLETE_TASK = "COMPLETE_TASK"
    ASSIGN_TASK = "ASSIGN_TASK"
    CREATE_REMINDER = "CREATE_REMINDER"
    CANCEL_REMINDER = "CANCEL_REMINDER"
    CREATE_AUTOMATION = "CREATE_AUTOMATION"
    UPDATE_AUTOMATION = "UPDATE_AUTOMATION"
    PAUSE_AUTOMATION = "PAUSE_AUTOMATION"
    RESUME_AUTOMATION = "RESUME_AUTOMATION"
    CANCEL_AUTOMATION = "CANCEL_AUTOMATION"
    SEND_DIRECT_MESSAGE = "SEND_DIRECT_MESSAGE"
    
    # Query Intents
    WORKSPACE_META_QUERY = "WORKSPACE_META_QUERY"
    TASK_QUERY = "TASK_QUERY"
    REMINDER_QUERY = "REMINDER_QUERY"
    AUTOMATION_QUERY = "AUTOMATION_QUERY"
    DM_QUERY = "DM_QUERY"
    PROJECT_QUERY = "PROJECT_QUERY"
    DECISION_QUERY = "DECISION_QUERY"
    DOCUMENT_QUERY = "DOCUMENT_QUERY"
    CONVERSATION_QUERY = "CONVERSATION_QUERY"
    SHARED_FILES_QUERY = "SHARED_FILES_QUERY"
    ACTION_HISTORY_QUERY = "ACTION_HISTORY_QUERY"
    GRAPH_QUERY = "GRAPH_QUERY"
    ACTIVITY_QUERY = "ACTIVITY_QUERY"
    MULTI_DOC_COMPARE = "MULTI_DOC_COMPARE"
    EXTRACTION_REQUEST = "EXTRACTION_REQUEST"
    SUMMARY_REQUEST = "SUMMARY_REQUEST"
    KNOWLEDGE_QUERY = "KNOWLEDGE_QUERY"
    
    # Conversational & General
    GENERAL_KNOWLEDGE = "GENERAL_KNOWLEDGE"
    GREETING = "GREETING"
    THANKS = "THANKS"
    CLARIFICATION_RESPONSE = "CLARIFICATION_RESPONSE"
    UNKNOWN = "UNKNOWN"

class RequestType(str, Enum):
    ACTION = "ACTION"
    QUERY = "QUERY"
    CONVERSATIONAL = "CONVERSATIONAL"
    GENERAL_KNOWLEDGE = "GENERAL_KNOWLEDGE"
    CLARIFICATION_RESPONSE = "CLARIFICATION_RESPONSE"

class CapabilityType(str, Enum):
    SQL_METADATA = "SQL_METADATA"
    TASK_SERVICE = "TASK_SERVICE"
    PROJECT_SERVICE = "PROJECT_SERVICE"
    DECISION_SERVICE = "DECISION_SERVICE"
    DOCUMENT_RAG = "DOCUMENT_RAG"
    MULTI_DOC_COMPARE = "MULTI_DOC_COMPARE"
    GRAPH_SERVICE = "GRAPH_SERVICE"
    ACTION_AUDIT_SERVICE = "ACTION_AUDIT_SERVICE"
    CONVERSATION_SEARCH_SERVICE = "CONVERSATION_SEARCH_SERVICE"
    SHARED_FILES_SERVICE = "SHARED_FILES_SERVICE"
    ACTION_WORKFLOW = "ACTION_WORKFLOW"
    GENERAL_LLM = "GENERAL_LLM"
    CONVERSATIONAL_SMALLTALK = "CONVERSATIONAL_SMALLTALK"
    CLARIFY = "CLARIFY"
    KNOWLEDGE_SYNTHESIS = "KNOWLEDGE_SYNTHESIS"
    TASK_EXTRACTION = "TASK_EXTRACTION"
    DISCUSSION_SUMMARY = "DISCUSSION_SUMMARY"

class RequestUnderstanding(BaseModel):
    intent: RequestIntent
    request_type: RequestType
    confidence: float = 1.0
    rewritten_query: Optional[str] = None
    entities: Dict[str, Any] = Field(default_factory=dict)
    temporal: Dict[str, Any] = Field(default_factory=dict)
    conversation_refs: Dict[str, Any] = Field(default_factory=dict)
    required_capability: CapabilityType
    missing_information: List[str] = Field(default_factory=list)
    ambiguity: Optional[str] = None
    response_mode: str = "DIRECT_ANSWER" # ACTION_PROPOSAL, GROUNDED_ANSWER, DIRECT_ANSWER, CLARIFICATION_PROMPT
    raw_query: str
