from sqlalchemy.orm import Mapped, mapped_column, relationship
from sqlalchemy import String, Text, ForeignKey, Boolean, JSON, DateTime, Integer
from uuid import UUID
from datetime import datetime
from typing import Optional, Dict, Any, List
from .base import BaseEntity


class CognitiveAgent(BaseEntity):
    """
    SQLAlchemy model for Cognitive Agent entity.
    Stores agent identity, scoping, instructions, status, and triggers.
    """
    __tablename__ = "cognitive_agents"

    organization_id: Mapped[UUID] = mapped_column(
        ForeignKey("organizations.id", ondelete="CASCADE"),
        index=True,
        nullable=False
    )
    workspace_id: Mapped[Optional[UUID]] = mapped_column(
        ForeignKey("workspaces.id", ondelete="CASCADE"),
        index=True,
        nullable=True
    )
    owner_user_id: Mapped[UUID] = mapped_column(
        ForeignKey("users.id", ondelete="CASCADE"),
        index=True,
        nullable=False
    )

    name: Mapped[str] = mapped_column(String(255), nullable=False)
    description: Mapped[Optional[str]] = mapped_column(Text, nullable=True)
    agent_type: Mapped[str] = mapped_column(String(50), nullable=False, default="CUSTOM")
    instructions: Mapped[str] = mapped_column(Text, nullable=False)
    status: Mapped[str] = mapped_column(String(30), nullable=False, default="ACTIVE", index=True)
    enabled: Mapped[bool] = mapped_column(Boolean, nullable=False, default=True)

    knowledge_scope: Mapped[Optional[Dict[str, Any]]] = mapped_column(JSON, nullable=True)
    triggers: Mapped[Optional[List[Dict[str, Any]]]] = mapped_column(JSON, nullable=True)

    executions: Mapped[List["CognitiveAgentExecution"]] = relationship(
        "CognitiveAgentExecution",
        back_populates="agent",
        cascade="all, delete-orphan",
        order_by="CognitiveAgentExecution.created_at.desc()"
    )
    outputs: Mapped[List["CognitiveAgentOutput"]] = relationship(
        "CognitiveAgentOutput",
        back_populates="agent",
        cascade="all, delete-orphan",
        order_by="CognitiveAgentOutput.created_at.desc()"
    )
    trigger_records: Mapped[List["CognitiveAgentTrigger"]] = relationship(
        "CognitiveAgentTrigger",
        back_populates="agent",
        cascade="all, delete-orphan",
        order_by="CognitiveAgentTrigger.created_at.desc()"
    )
    memories: Mapped[List["CognitiveAgentMemory"]] = relationship(
        "CognitiveAgentMemory",
        back_populates="agent",
        cascade="all, delete-orphan",
        order_by="CognitiveAgentMemory.created_at.desc()"
    )


class CognitiveAgentExecution(BaseEntity):
    """
    SQLAlchemy model for tracking Cognitive Agent execution history.
    """
    __tablename__ = "cognitive_agent_executions"

    agent_id: Mapped[UUID] = mapped_column(
        ForeignKey("cognitive_agents.id", ondelete="CASCADE"),
        index=True,
        nullable=False
    )
    organization_id: Mapped[UUID] = mapped_column(
        ForeignKey("organizations.id", ondelete="CASCADE"),
        index=True,
        nullable=False
    )
    workspace_id: Mapped[Optional[UUID]] = mapped_column(
        ForeignKey("workspaces.id", ondelete="CASCADE"),
        index=True,
        nullable=True
    )
    triggered_by: Mapped[Optional[UUID]] = mapped_column(
        ForeignKey("users.id", ondelete="SET NULL"),
        nullable=True
    )

    trigger_type: Mapped[str] = mapped_column(String(50), nullable=False, default="MANUAL")
    status: Mapped[str] = mapped_column(String(30), nullable=False, default="QUEUED", index=True)

    started_at: Mapped[datetime] = mapped_column(DateTime, default=datetime.utcnow, nullable=False)
    completed_at: Mapped[Optional[datetime]] = mapped_column(DateTime, nullable=True)

    input_context: Mapped[Optional[Dict[str, Any]]] = mapped_column(JSON, nullable=True)
    output_summary: Mapped[Optional[str]] = mapped_column(Text, nullable=True)
    action_candidates_generated: Mapped[int] = mapped_column(Integer, nullable=False, default=0)
    error_message: Mapped[Optional[str]] = mapped_column(Text, nullable=True)

    agent: Mapped["CognitiveAgent"] = relationship("CognitiveAgent", back_populates="executions")
    outputs: Mapped[List["CognitiveAgentOutput"]] = relationship(
        "CognitiveAgentOutput",
        back_populates="execution",
        cascade="all, delete-orphan"
    )


class CognitiveAgentOutput(BaseEntity):
    """
    SQLAlchemy model for outputs generated by Cognitive Agent executions.
    """
    __tablename__ = "cognitive_agent_outputs"

    execution_id: Mapped[UUID] = mapped_column(
        ForeignKey("cognitive_agent_executions.id", ondelete="CASCADE"),
        index=True,
        nullable=False
    )
    agent_id: Mapped[UUID] = mapped_column(
        ForeignKey("cognitive_agents.id", ondelete="CASCADE"),
        index=True,
        nullable=False
    )
    organization_id: Mapped[UUID] = mapped_column(
        ForeignKey("organizations.id", ondelete="CASCADE"),
        index=True,
        nullable=False
    )
    workspace_id: Mapped[Optional[UUID]] = mapped_column(
        ForeignKey("workspaces.id", ondelete="CASCADE"),
        index=True,
        nullable=True
    )

    output_type: Mapped[str] = mapped_column(String(50), nullable=False, default="INSIGHT", index=True)
    title: Mapped[str] = mapped_column(String(255), nullable=False)
    body: Mapped[str] = mapped_column(Text, nullable=False)

    candidate_type: Mapped[Optional[str]] = mapped_column(String(50), nullable=True)
    structured_payload: Mapped[Optional[Dict[str, Any]]] = mapped_column(JSON, nullable=True)
    provenance: Mapped[Optional[List[Dict[str, Any]]]] = mapped_column(JSON, nullable=True)

    agent: Mapped["CognitiveAgent"] = relationship("CognitiveAgent", back_populates="outputs")
    execution: Mapped["CognitiveAgentExecution"] = relationship("CognitiveAgentExecution", back_populates="outputs")


class CognitiveAgentTrigger(BaseEntity):
    """
    SQLAlchemy model for Cognitive Agent Triggers & Schedules (CA-06).
    """
    __tablename__ = "cognitive_agent_triggers"

    agent_id: Mapped[UUID] = mapped_column(
        ForeignKey("cognitive_agents.id", ondelete="CASCADE"),
        index=True,
        nullable=False
    )
    organization_id: Mapped[UUID] = mapped_column(
        ForeignKey("organizations.id", ondelete="CASCADE"),
        index=True,
        nullable=False
    )
    workspace_id: Mapped[Optional[UUID]] = mapped_column(
        ForeignKey("workspaces.id", ondelete="CASCADE"),
        index=True,
        nullable=True
    )
    created_by_user_id: Mapped[Optional[UUID]] = mapped_column(
        ForeignKey("users.id", ondelete="SET NULL"),
        nullable=True
    )

    trigger_type: Mapped[str] = mapped_column(String(30), nullable=False, default="SCHEDULE", index=True)
    status: Mapped[str] = mapped_column(String(30), nullable=False, default="ACTIVE", index=True)

    schedule_type: Mapped[Optional[str]] = mapped_column(String(30), nullable=True)
    time_str: Mapped[Optional[str]] = mapped_column(String(20), nullable=True)
    day_of_week: Mapped[Optional[str]] = mapped_column(String(20), nullable=True)
    timezone: Mapped[str] = mapped_column(String(50), nullable=False, default="Asia/Kolkata")

    event_type: Mapped[Optional[str]] = mapped_column(String(50), nullable=True, index=True)
    event_filters: Mapped[Optional[Dict[str, Any]]] = mapped_column(JSON, nullable=True)

    next_run_at: Mapped[Optional[datetime]] = mapped_column(DateTime, nullable=True, index=True)
    last_run_at: Mapped[Optional[datetime]] = mapped_column(DateTime, nullable=True)
    last_execution_id: Mapped[Optional[UUID]] = mapped_column(
        ForeignKey("cognitive_agent_executions.id", ondelete="SET NULL"),
        nullable=True
    )

    agent: Mapped["CognitiveAgent"] = relationship("CognitiveAgent", back_populates="trigger_records")


class CognitiveAgentMemory(BaseEntity):
    """
    SQLAlchemy model for Cognitive Agent Durable Memory (CA-09).
    Stores durable, provenance-backed agent memory records with status lifecycle (ACTIVE, SUPERSEDED, EXPIRED, CONFLICT).
    """
    __tablename__ = "cognitive_agent_memories"

    agent_id: Mapped[UUID] = mapped_column(
        ForeignKey("cognitive_agents.id", ondelete="CASCADE"),
        index=True,
        nullable=False
    )
    organization_id: Mapped[UUID] = mapped_column(
        ForeignKey("organizations.id", ondelete="CASCADE"),
        index=True,
        nullable=False
    )
    workspace_id: Mapped[Optional[UUID]] = mapped_column(
        ForeignKey("workspaces.id", ondelete="CASCADE"),
        index=True,
        nullable=True
    )
    created_by_user_id: Mapped[Optional[UUID]] = mapped_column(
        ForeignKey("users.id", ondelete="SET NULL"),
        nullable=True
    )

    memory_type: Mapped[str] = mapped_column(String(30), nullable=False, default="EPISODIC", index=True) # EPISODIC, SEMANTIC, TASK_CONTEXT, PREFERENCE
    status: Mapped[str] = mapped_column(String(30), nullable=False, default="ACTIVE", index=True) # ACTIVE, SUPERSEDED, EXPIRED, CONFLICT

    key: Mapped[str] = mapped_column(String(255), nullable=False, index=True)
    content: Mapped[str] = mapped_column(Text, nullable=False)

    confidence: Mapped[float] = mapped_column(JSON, nullable=True, default=0.9)
    confidence_level: Mapped[str] = mapped_column(String(30), nullable=False, default="CONFIRMED") # CONFIRMED, OBSERVED, INFERRED

    source_execution_id: Mapped[Optional[UUID]] = mapped_column(
        ForeignKey("cognitive_agent_executions.id", ondelete="SET NULL"),
        nullable=True
    )
    source_output_id: Mapped[Optional[UUID]] = mapped_column(
        ForeignKey("cognitive_agent_outputs.id", ondelete="SET NULL"),
        nullable=True
    )
    source_entity_type: Mapped[Optional[str]] = mapped_column(String(50), nullable=True)
    source_entity_id: Mapped[Optional[str]] = mapped_column(String(255), nullable=True)

    superseded_by_id: Mapped[Optional[UUID]] = mapped_column(nullable=True)
    expired_at: Mapped[Optional[datetime]] = mapped_column(DateTime, nullable=True)

    agent: Mapped["CognitiveAgent"] = relationship("CognitiveAgent", back_populates="memories")


