"""add_memory_and_governance_tables

Revision ID: 0d0565c3c2af
Revises: 3195fc889c70
Create Date: 2026-07-19 10:54:53.439887

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0d0565c3c2af'
down_revision: Union[str, None] = '3195fc889c70'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('agent_feedback',
    sa.Column('execution_id', sa.Uuid(), nullable=True),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('organization_id', sa.Uuid(), nullable=False),
    sa.Column('feedback_type', sa.String(), nullable=False),
    sa.Column('rating', sa.Integer(), nullable=False),
    sa.Column('comment', sa.String(), nullable=True),
    sa.Column('context_data', sa.JSON(), nullable=True),
    sa.Column('processed', sa.Boolean(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('created_by', sa.String(), nullable=True),
    sa.Column('updated_by', sa.String(), nullable=True),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_agent_feedback_execution_id'), 'agent_feedback', ['execution_id'], unique=False)
    op.create_index(op.f('ix_agent_feedback_organization_id'), 'agent_feedback', ['organization_id'], unique=False)
    op.create_index(op.f('ix_agent_feedback_user_id'), 'agent_feedback', ['user_id'], unique=False)
    op.create_table('audit_decision_logs',
    sa.Column('execution_id', sa.Uuid(), nullable=False),
    sa.Column('organization_id', sa.Uuid(), nullable=False),
    sa.Column('agent_name', sa.String(), nullable=False),
    sa.Column('selected_tools', sa.JSON(), nullable=False),
    sa.Column('retrieved_documents', sa.JSON(), nullable=False),
    sa.Column('applied_policies', sa.JSON(), nullable=False),
    sa.Column('confidence_score', sa.Float(), nullable=False),
    sa.Column('risk_score', sa.Float(), nullable=False),
    sa.Column('trust_score', sa.Float(), nullable=False),
    sa.Column('execution_summary', sa.String(), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('created_by', sa.String(), nullable=True),
    sa.Column('updated_by', sa.String(), nullable=True),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_audit_decision_logs_execution_id'), 'audit_decision_logs', ['execution_id'], unique=False)
    op.create_index(op.f('ix_audit_decision_logs_organization_id'), 'audit_decision_logs', ['organization_id'], unique=False)
    op.create_table('governance_policies',
    sa.Column('organization_id', sa.Uuid(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('category', sa.String(), nullable=False),
    sa.Column('rules', sa.JSON(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('created_by', sa.String(), nullable=True),
    sa.Column('updated_by', sa.String(), nullable=True),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_governance_policies_category'), 'governance_policies', ['category'], unique=False)
    op.create_index(op.f('ix_governance_policies_organization_id'), 'governance_policies', ['organization_id'], unique=False)
    op.create_table('workflows',
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('definition', sa.JSON(), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('organization_id', sa.Uuid(), nullable=False),
    sa.Column('workspace_id', sa.Uuid(), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('created_by', sa.String(), nullable=True),
    sa.Column('updated_by', sa.String(), nullable=True),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspaces.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_workflows_organization_id'), 'workflows', ['organization_id'], unique=False)
    op.create_table('long_term_memories',
    sa.Column('memory_type', sa.String(), nullable=False),
    sa.Column('scope_key', sa.String(), nullable=False),
    sa.Column('organization_id', sa.Uuid(), nullable=False),
    sa.Column('workspace_id', sa.Uuid(), nullable=True),
    sa.Column('project_id', sa.Uuid(), nullable=True),
    sa.Column('key', sa.String(), nullable=False),
    sa.Column('value', sa.JSON(), nullable=False),
    sa.Column('importance_score', sa.Float(), nullable=False),
    sa.Column('confidence_score', sa.Float(), nullable=False),
    sa.Column('retention_expires_at', sa.DateTime(), nullable=True),
    sa.Column('last_accessed_at', sa.DateTime(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('created_by', sa.String(), nullable=True),
    sa.Column('updated_by', sa.String(), nullable=True),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspaces.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_long_term_memories_key'), 'long_term_memories', ['key'], unique=False)
    op.create_index(op.f('ix_long_term_memories_memory_type'), 'long_term_memories', ['memory_type'], unique=False)
    op.create_index(op.f('ix_long_term_memories_organization_id'), 'long_term_memories', ['organization_id'], unique=False)
    op.create_index(op.f('ix_long_term_memories_scope_key'), 'long_term_memories', ['scope_key'], unique=False)
    op.create_table('workflow_executions',
    sa.Column('workflow_id', sa.Uuid(), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('context', sa.JSON(), nullable=False),
    sa.Column('current_step_index', sa.Integer(), nullable=False),
    sa.Column('started_at', sa.DateTime(), nullable=True),
    sa.Column('completed_at', sa.DateTime(), nullable=True),
    sa.Column('error', sa.Text(), nullable=True),
    sa.Column('organization_id', sa.Uuid(), nullable=False),
    sa.Column('workspace_id', sa.Uuid(), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('created_by', sa.String(), nullable=True),
    sa.Column('updated_by', sa.String(), nullable=True),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['workflow_id'], ['workflows.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspaces.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_workflow_executions_organization_id'), 'workflow_executions', ['organization_id'], unique=False)
    op.create_index(op.f('ix_workflow_executions_workflow_id'), 'workflow_executions', ['workflow_id'], unique=False)
    op.create_table('workflow_schedules',
    sa.Column('workflow_id', sa.Uuid(), nullable=False),
    sa.Column('schedule_type', sa.String(length=50), nullable=False),
    sa.Column('expression', sa.String(length=100), nullable=False),
    sa.Column('next_run_at', sa.DateTime(), nullable=False),
    sa.Column('organization_id', sa.Uuid(), nullable=False),
    sa.Column('workspace_id', sa.Uuid(), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('created_by', sa.String(), nullable=True),
    sa.Column('updated_by', sa.String(), nullable=True),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['workflow_id'], ['workflows.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspaces.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_workflow_schedules_organization_id'), 'workflow_schedules', ['organization_id'], unique=False)
    op.create_index(op.f('ix_workflow_schedules_workflow_id'), 'workflow_schedules', ['workflow_id'], unique=False)
    op.create_table('automation_events',
    sa.Column('event_type', sa.String(length=100), nullable=False),
    sa.Column('payload', sa.JSON(), nullable=False),
    sa.Column('processed', sa.Boolean(), nullable=False),
    sa.Column('triggered_workflow_id', sa.Uuid(), nullable=True),
    sa.Column('organization_id', sa.Uuid(), nullable=False),
    sa.Column('workspace_id', sa.Uuid(), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('created_by', sa.String(), nullable=True),
    sa.Column('updated_by', sa.String(), nullable=True),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['triggered_workflow_id'], ['workflow_executions.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspaces.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_automation_events_organization_id'), 'automation_events', ['organization_id'], unique=False)
    op.create_table('workflow_approvals',
    sa.Column('workflow_execution_id', sa.Uuid(), nullable=True),
    sa.Column('step_name', sa.String(length=100), nullable=True),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('assigned_approver', sa.String(length=100), nullable=True),
    sa.Column('policy_type', sa.String(length=50), nullable=False),
    sa.Column('approvers_voted', sa.JSON(), nullable=False),
    sa.Column('decision_by', sa.String(length=100), nullable=True),
    sa.Column('decision_at', sa.DateTime(), nullable=True),
    sa.Column('comments', sa.Text(), nullable=True),
    sa.Column('escalated_to', sa.String(length=100), nullable=True),
    sa.Column('delegated_to', sa.String(length=100), nullable=True),
    sa.Column('escalated_at', sa.DateTime(), nullable=True),
    sa.Column('sla_limit_hours', sa.Integer(), nullable=True),
    sa.Column('organization_id', sa.Uuid(), nullable=False),
    sa.Column('workspace_id', sa.Uuid(), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('created_by', sa.String(), nullable=True),
    sa.Column('updated_by', sa.String(), nullable=True),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['workflow_execution_id'], ['workflow_executions.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspaces.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_workflow_approvals_organization_id'), 'workflow_approvals', ['organization_id'], unique=False)
    op.create_index(op.f('ix_workflow_approvals_workflow_execution_id'), 'workflow_approvals', ['workflow_execution_id'], unique=False)
    op.create_table('workflow_step_executions',
    sa.Column('execution_id', sa.Uuid(), nullable=False),
    sa.Column('step_name', sa.String(length=100), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('started_at', sa.DateTime(), nullable=False),
    sa.Column('completed_at', sa.DateTime(), nullable=True),
    sa.Column('duration_ms', sa.Float(), nullable=True),
    sa.Column('error', sa.Text(), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('created_by', sa.String(), nullable=True),
    sa.Column('updated_by', sa.String(), nullable=True),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['execution_id'], ['workflow_executions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_workflow_step_executions_execution_id'), 'workflow_step_executions', ['execution_id'], unique=False)
    op.alter_column('activity_logs', 'created_by',
               existing_type=sa.UUID(),
               type_=sa.String(),
               existing_nullable=True)
    op.alter_column('activity_logs', 'updated_by',
               existing_type=sa.UUID(),
               type_=sa.String(),
               existing_nullable=True)
    op.create_index(op.f('ix_agent_memory_agent_id'), 'agent_memory', ['agent_id'], unique=False)
    op.create_index(op.f('ix_agent_memory_organization_id'), 'agent_memory', ['organization_id'], unique=False)
    op.create_index(op.f('ix_agents_organization_id'), 'agents', ['organization_id'], unique=False)
    op.create_index(op.f('ix_audit_logs_organization_id'), 'audit_logs', ['organization_id'], unique=False)
    op.create_index(op.f('ix_audit_logs_user_id'), 'audit_logs', ['user_id'], unique=False)
    op.create_index(op.f('ix_chats_organization_id'), 'chats', ['organization_id'], unique=False)
    op.drop_constraint('conversation_memories_chat_id_key', 'conversation_memories', type_='unique')
    op.drop_index('ix_conversation_memories_chat_id', table_name='conversation_memories')
    op.create_index(op.f('ix_conversation_memories_chat_id'), 'conversation_memories', ['chat_id'], unique=True)
    op.alter_column('document_audit_logs', 'created_by',
               existing_type=sa.UUID(),
               type_=sa.String(),
               existing_nullable=True)
    op.alter_column('document_audit_logs', 'updated_by',
               existing_type=sa.UUID(),
               type_=sa.String(),
               existing_nullable=True)
    op.alter_column('document_chunks', 'created_by',
               existing_type=sa.UUID(),
               type_=sa.String(),
               existing_nullable=True)
    op.alter_column('document_chunks', 'updated_by',
               existing_type=sa.UUID(),
               type_=sa.String(),
               existing_nullable=True)
    op.alter_column('document_contents', 'created_by',
               existing_type=sa.UUID(),
               type_=sa.String(),
               existing_nullable=True)
    op.alter_column('document_contents', 'updated_by',
               existing_type=sa.UUID(),
               type_=sa.String(),
               existing_nullable=True)
    op.drop_constraint('document_contents_document_id_key', 'document_contents', type_='unique')
    op.drop_index('ix_document_contents_document_id', table_name='document_contents')
    op.create_index(op.f('ix_document_contents_document_id'), 'document_contents', ['document_id'], unique=True)
    op.alter_column('document_embeddings', 'created_by',
               existing_type=sa.UUID(),
               type_=sa.String(),
               existing_nullable=True)
    op.alter_column('document_embeddings', 'updated_by',
               existing_type=sa.UUID(),
               type_=sa.String(),
               existing_nullable=True)
    op.drop_constraint('document_embeddings_chunk_id_key', 'document_embeddings', type_='unique')
    op.drop_index('ix_document_embeddings_chunk_id', table_name='document_embeddings')
    op.create_index(op.f('ix_document_embeddings_chunk_id'), 'document_embeddings', ['chunk_id'], unique=True)
    op.alter_column('document_metadata', 'created_by',
               existing_type=sa.UUID(),
               type_=sa.String(),
               existing_nullable=True)
    op.alter_column('document_metadata', 'updated_by',
               existing_type=sa.UUID(),
               type_=sa.String(),
               existing_nullable=True)
    op.drop_constraint('document_metadata_document_id_key', 'document_metadata', type_='unique')
    op.drop_index('ix_document_metadata_document_id', table_name='document_metadata')
    op.create_index(op.f('ix_document_metadata_document_id'), 'document_metadata', ['document_id'], unique=True)
    op.alter_column('document_statistics', 'created_by',
               existing_type=sa.UUID(),
               type_=sa.String(),
               existing_nullable=True)
    op.alter_column('document_statistics', 'updated_by',
               existing_type=sa.UUID(),
               type_=sa.String(),
               existing_nullable=True)
    op.drop_constraint('document_statistics_document_id_key', 'document_statistics', type_='unique')
    op.alter_column('document_upload_jobs', 'created_by',
               existing_type=sa.UUID(),
               type_=sa.String(),
               existing_nullable=True)
    op.alter_column('document_upload_jobs', 'updated_by',
               existing_type=sa.UUID(),
               type_=sa.String(),
               existing_nullable=True)
    op.alter_column('document_versions', 'created_by',
               existing_type=sa.UUID(),
               type_=sa.String(),
               existing_nullable=True)
    op.alter_column('document_versions', 'updated_by',
               existing_type=sa.UUID(),
               type_=sa.String(),
               existing_nullable=True)
    op.alter_column('documents', 'created_by',
               existing_type=sa.UUID(),
               type_=sa.String(),
               existing_nullable=True)
    op.alter_column('documents', 'updated_by',
               existing_type=sa.UUID(),
               type_=sa.String(),
               existing_nullable=True)
    op.alter_column('embedding_jobs', 'created_by',
               existing_type=sa.UUID(),
               type_=sa.String(),
               existing_nullable=True)
    op.alter_column('embedding_jobs', 'updated_by',
               existing_type=sa.UUID(),
               type_=sa.String(),
               existing_nullable=True)
    op.alter_column('knowledge_entries', 'created_by',
               existing_type=sa.UUID(),
               type_=sa.String(),
               existing_nullable=True)
    op.alter_column('knowledge_entries', 'updated_by',
               existing_type=sa.UUID(),
               type_=sa.String(),
               existing_nullable=True)
    op.drop_constraint('knowledge_entries_document_id_key', 'knowledge_entries', type_='unique')
    op.drop_index('ix_knowledge_entries_document_id', table_name='knowledge_entries')
    op.create_index(op.f('ix_knowledge_entries_document_id'), 'knowledge_entries', ['document_id'], unique=True)
    op.create_index(op.f('ix_messages_chat_id'), 'messages', ['chat_id'], unique=False)
    op.create_index(op.f('ix_messages_organization_id'), 'messages', ['organization_id'], unique=False)
    op.create_index(op.f('ix_messages_sender_id'), 'messages', ['sender_id'], unique=False)
    op.alter_column('notifications', 'created_by',
               existing_type=sa.UUID(),
               type_=sa.String(),
               existing_nullable=True)
    op.alter_column('notifications', 'updated_by',
               existing_type=sa.UUID(),
               type_=sa.String(),
               existing_nullable=True)
    op.create_index(op.f('ix_organization_members_organization_id'), 'organization_members', ['organization_id'], unique=False)
    op.create_index(op.f('ix_organization_members_role_id'), 'organization_members', ['role_id'], unique=False)
    op.create_index(op.f('ix_organization_members_user_id'), 'organization_members', ['user_id'], unique=False)
    op.alter_column('processing_events', 'created_by',
               existing_type=sa.UUID(),
               type_=sa.String(),
               existing_nullable=True)
    op.alter_column('processing_events', 'updated_by',
               existing_type=sa.UUID(),
               type_=sa.String(),
               existing_nullable=True)
    op.create_index(op.f('ix_projects_organization_id'), 'projects', ['organization_id'], unique=False)
    op.create_index(op.f('ix_projects_slug'), 'projects', ['slug'], unique=False)
    op.create_index(op.f('ix_projects_workspace_id'), 'projects', ['workspace_id'], unique=False)
    op.create_index(op.f('ix_refresh_tokens_user_id'), 'refresh_tokens', ['user_id'], unique=False)
    op.alter_column('retention_policies', 'created_by',
               existing_type=sa.UUID(),
               type_=sa.String(),
               existing_nullable=True)
    op.alter_column('retention_policies', 'updated_by',
               existing_type=sa.UUID(),
               type_=sa.String(),
               existing_nullable=True)
    op.create_index(op.f('ix_tasks_organization_id'), 'tasks', ['organization_id'], unique=False)
    op.alter_column('vector_indexes', 'created_by',
               existing_type=sa.UUID(),
               type_=sa.String(),
               existing_nullable=True)
    op.alter_column('vector_indexes', 'updated_by',
               existing_type=sa.UUID(),
               type_=sa.String(),
               existing_nullable=True)
    op.create_index(op.f('ix_workspaces_organization_id'), 'workspaces', ['organization_id'], unique=False)
    op.create_index(op.f('ix_workspaces_slug'), 'workspaces', ['slug'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_workspaces_slug'), table_name='workspaces')
    op.drop_index(op.f('ix_workspaces_organization_id'), table_name='workspaces')
    op.alter_column('vector_indexes', 'updated_by',
               existing_type=sa.String(),
               type_=sa.UUID(),
               existing_nullable=True)
    op.alter_column('vector_indexes', 'created_by',
               existing_type=sa.String(),
               type_=sa.UUID(),
               existing_nullable=True)
    op.drop_index(op.f('ix_tasks_organization_id'), table_name='tasks')
    op.alter_column('retention_policies', 'updated_by',
               existing_type=sa.String(),
               type_=sa.UUID(),
               existing_nullable=True)
    op.alter_column('retention_policies', 'created_by',
               existing_type=sa.String(),
               type_=sa.UUID(),
               existing_nullable=True)
    op.drop_index(op.f('ix_refresh_tokens_user_id'), table_name='refresh_tokens')
    op.drop_index(op.f('ix_projects_workspace_id'), table_name='projects')
    op.drop_index(op.f('ix_projects_slug'), table_name='projects')
    op.drop_index(op.f('ix_projects_organization_id'), table_name='projects')
    op.alter_column('processing_events', 'updated_by',
               existing_type=sa.String(),
               type_=sa.UUID(),
               existing_nullable=True)
    op.alter_column('processing_events', 'created_by',
               existing_type=sa.String(),
               type_=sa.UUID(),
               existing_nullable=True)
    op.drop_index(op.f('ix_organization_members_user_id'), table_name='organization_members')
    op.drop_index(op.f('ix_organization_members_role_id'), table_name='organization_members')
    op.drop_index(op.f('ix_organization_members_organization_id'), table_name='organization_members')
    op.alter_column('notifications', 'updated_by',
               existing_type=sa.String(),
               type_=sa.UUID(),
               existing_nullable=True)
    op.alter_column('notifications', 'created_by',
               existing_type=sa.String(),
               type_=sa.UUID(),
               existing_nullable=True)
    op.drop_index(op.f('ix_messages_sender_id'), table_name='messages')
    op.drop_index(op.f('ix_messages_organization_id'), table_name='messages')
    op.drop_index(op.f('ix_messages_chat_id'), table_name='messages')
    op.drop_index(op.f('ix_knowledge_entries_document_id'), table_name='knowledge_entries')
    op.create_index('ix_knowledge_entries_document_id', 'knowledge_entries', ['document_id'], unique=False)
    op.create_unique_constraint('knowledge_entries_document_id_key', 'knowledge_entries', ['document_id'], postgresql_nulls_not_distinct=False)
    op.alter_column('knowledge_entries', 'updated_by',
               existing_type=sa.String(),
               type_=sa.UUID(),
               existing_nullable=True)
    op.alter_column('knowledge_entries', 'created_by',
               existing_type=sa.String(),
               type_=sa.UUID(),
               existing_nullable=True)
    op.alter_column('embedding_jobs', 'updated_by',
               existing_type=sa.String(),
               type_=sa.UUID(),
               existing_nullable=True)
    op.alter_column('embedding_jobs', 'created_by',
               existing_type=sa.String(),
               type_=sa.UUID(),
               existing_nullable=True)
    op.alter_column('documents', 'updated_by',
               existing_type=sa.String(),
               type_=sa.UUID(),
               existing_nullable=True)
    op.alter_column('documents', 'created_by',
               existing_type=sa.String(),
               type_=sa.UUID(),
               existing_nullable=True)
    op.alter_column('document_versions', 'updated_by',
               existing_type=sa.String(),
               type_=sa.UUID(),
               existing_nullable=True)
    op.alter_column('document_versions', 'created_by',
               existing_type=sa.String(),
               type_=sa.UUID(),
               existing_nullable=True)
    op.alter_column('document_upload_jobs', 'updated_by',
               existing_type=sa.String(),
               type_=sa.UUID(),
               existing_nullable=True)
    op.alter_column('document_upload_jobs', 'created_by',
               existing_type=sa.String(),
               type_=sa.UUID(),
               existing_nullable=True)
    op.create_unique_constraint('document_statistics_document_id_key', 'document_statistics', ['document_id'], postgresql_nulls_not_distinct=False)
    op.alter_column('document_statistics', 'updated_by',
               existing_type=sa.String(),
               type_=sa.UUID(),
               existing_nullable=True)
    op.alter_column('document_statistics', 'created_by',
               existing_type=sa.String(),
               type_=sa.UUID(),
               existing_nullable=True)
    op.drop_index(op.f('ix_document_metadata_document_id'), table_name='document_metadata')
    op.create_index('ix_document_metadata_document_id', 'document_metadata', ['document_id'], unique=False)
    op.create_unique_constraint('document_metadata_document_id_key', 'document_metadata', ['document_id'], postgresql_nulls_not_distinct=False)
    op.alter_column('document_metadata', 'updated_by',
               existing_type=sa.String(),
               type_=sa.UUID(),
               existing_nullable=True)
    op.alter_column('document_metadata', 'created_by',
               existing_type=sa.String(),
               type_=sa.UUID(),
               existing_nullable=True)
    op.drop_index(op.f('ix_document_embeddings_chunk_id'), table_name='document_embeddings')
    op.create_index('ix_document_embeddings_chunk_id', 'document_embeddings', ['chunk_id'], unique=False)
    op.create_unique_constraint('document_embeddings_chunk_id_key', 'document_embeddings', ['chunk_id'], postgresql_nulls_not_distinct=False)
    op.alter_column('document_embeddings', 'updated_by',
               existing_type=sa.String(),
               type_=sa.UUID(),
               existing_nullable=True)
    op.alter_column('document_embeddings', 'created_by',
               existing_type=sa.String(),
               type_=sa.UUID(),
               existing_nullable=True)
    op.drop_index(op.f('ix_document_contents_document_id'), table_name='document_contents')
    op.create_index('ix_document_contents_document_id', 'document_contents', ['document_id'], unique=False)
    op.create_unique_constraint('document_contents_document_id_key', 'document_contents', ['document_id'], postgresql_nulls_not_distinct=False)
    op.alter_column('document_contents', 'updated_by',
               existing_type=sa.String(),
               type_=sa.UUID(),
               existing_nullable=True)
    op.alter_column('document_contents', 'created_by',
               existing_type=sa.String(),
               type_=sa.UUID(),
               existing_nullable=True)
    op.alter_column('document_chunks', 'updated_by',
               existing_type=sa.String(),
               type_=sa.UUID(),
               existing_nullable=True)
    op.alter_column('document_chunks', 'created_by',
               existing_type=sa.String(),
               type_=sa.UUID(),
               existing_nullable=True)
    op.alter_column('document_audit_logs', 'updated_by',
               existing_type=sa.String(),
               type_=sa.UUID(),
               existing_nullable=True)
    op.alter_column('document_audit_logs', 'created_by',
               existing_type=sa.String(),
               type_=sa.UUID(),
               existing_nullable=True)
    op.drop_index(op.f('ix_conversation_memories_chat_id'), table_name='conversation_memories')
    op.create_index('ix_conversation_memories_chat_id', 'conversation_memories', ['chat_id'], unique=False)
    op.create_unique_constraint('conversation_memories_chat_id_key', 'conversation_memories', ['chat_id'], postgresql_nulls_not_distinct=False)
    op.drop_index(op.f('ix_chats_organization_id'), table_name='chats')
    op.drop_index(op.f('ix_audit_logs_user_id'), table_name='audit_logs')
    op.drop_index(op.f('ix_audit_logs_organization_id'), table_name='audit_logs')
    op.drop_index(op.f('ix_agents_organization_id'), table_name='agents')
    op.drop_index(op.f('ix_agent_memory_organization_id'), table_name='agent_memory')
    op.drop_index(op.f('ix_agent_memory_agent_id'), table_name='agent_memory')
    op.alter_column('activity_logs', 'updated_by',
               existing_type=sa.String(),
               type_=sa.UUID(),
               existing_nullable=True)
    op.alter_column('activity_logs', 'created_by',
               existing_type=sa.String(),
               type_=sa.UUID(),
               existing_nullable=True)
    op.drop_index(op.f('ix_workflow_step_executions_execution_id'), table_name='workflow_step_executions')
    op.drop_table('workflow_step_executions')
    op.drop_index(op.f('ix_workflow_approvals_workflow_execution_id'), table_name='workflow_approvals')
    op.drop_index(op.f('ix_workflow_approvals_organization_id'), table_name='workflow_approvals')
    op.drop_table('workflow_approvals')
    op.drop_index(op.f('ix_automation_events_organization_id'), table_name='automation_events')
    op.drop_table('automation_events')
    op.drop_index(op.f('ix_workflow_schedules_workflow_id'), table_name='workflow_schedules')
    op.drop_index(op.f('ix_workflow_schedules_organization_id'), table_name='workflow_schedules')
    op.drop_table('workflow_schedules')
    op.drop_index(op.f('ix_workflow_executions_workflow_id'), table_name='workflow_executions')
    op.drop_index(op.f('ix_workflow_executions_organization_id'), table_name='workflow_executions')
    op.drop_table('workflow_executions')
    op.drop_index(op.f('ix_long_term_memories_scope_key'), table_name='long_term_memories')
    op.drop_index(op.f('ix_long_term_memories_organization_id'), table_name='long_term_memories')
    op.drop_index(op.f('ix_long_term_memories_memory_type'), table_name='long_term_memories')
    op.drop_index(op.f('ix_long_term_memories_key'), table_name='long_term_memories')
    op.drop_table('long_term_memories')
    op.drop_index(op.f('ix_workflows_organization_id'), table_name='workflows')
    op.drop_table('workflows')
    op.drop_index(op.f('ix_governance_policies_organization_id'), table_name='governance_policies')
    op.drop_index(op.f('ix_governance_policies_category'), table_name='governance_policies')
    op.drop_table('governance_policies')
    op.drop_index(op.f('ix_audit_decision_logs_organization_id'), table_name='audit_decision_logs')
    op.drop_index(op.f('ix_audit_decision_logs_execution_id'), table_name='audit_decision_logs')
    op.drop_table('audit_decision_logs')
    op.drop_index(op.f('ix_agent_feedback_user_id'), table_name='agent_feedback')
    op.drop_index(op.f('ix_agent_feedback_organization_id'), table_name='agent_feedback')
    op.drop_index(op.f('ix_agent_feedback_execution_id'), table_name='agent_feedback')
    op.drop_table('agent_feedback')
    # ### end Alembic commands ###
