"""add_org_workspace_management

Revision ID: a219729b1ea7
Revises: 0d0565c3c2af
Create Date: 2026-07-19 18:22:22.278992

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a219729b1ea7'
down_revision: Union[str, None] = '0d0565c3c2af'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('chats', sa.Column('workspace_id', sa.Uuid(), nullable=True))
    op.create_index(op.f('ix_chats_workspace_id'), 'chats', ['workspace_id'], unique=False)
    op.create_foreign_key(None, 'chats', 'workspaces', ['workspace_id'], ['id'], ondelete='CASCADE')
    op.add_column('organizations', sa.Column('logo_url', sa.String(), nullable=True))
    op.add_column('users', sa.Column('current_organization_id', sa.Uuid(), nullable=True))
    op.add_column('users', sa.Column('current_workspace_id', sa.Uuid(), nullable=True))
    op.create_foreign_key(None, 'users', 'organizations', ['current_organization_id'], ['id'], ondelete='SET NULL')
    op.create_foreign_key(None, 'users', 'workspaces', ['current_workspace_id'], ['id'], ondelete='SET NULL')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'users', type_='foreignkey')
    op.drop_constraint(None, 'users', type_='foreignkey')
    op.drop_column('users', 'current_workspace_id')
    op.drop_column('users', 'current_organization_id')
    op.drop_column('organizations', 'logo_url')
    op.drop_constraint(None, 'chats', type_='foreignkey')
    op.drop_index(op.f('ix_chats_workspace_id'), table_name='chats')
    op.drop_column('chats', 'workspace_id')
    # ### end Alembic commands ###
